version: 0.2

phases:
  build:
    commands:

     - echo Entered the build phase...
     - mvn DskipTests clean package
  post_build:
    commands:
     - echo Build completed successfully
artifacts:
  files:
      - target/audit-severity.jar
  discard-paths: yes